variable "tag" {}
variable "az-1a" {}
variable "az-1c" {}
variable "vpc_cidr" {}
variable "public1_cidr" {}
variable "public2_cidr" {}
variable "private1_cidr" {}
variable "private2_cidr" {}
variable "all_cidr" {}